default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    sh("cd .. && npm test -- --runInBand")
  end

  desc "Build iOS release"
  lane :release do
    test
    sh("cd .. && bundle exec pod install --project-directory=ios")
    build_app(
      scheme: "ConstructTrack",
      export_method: "app-store"
    )
  end
end

platform :android do
  desc "Build Android release bundle"
  lane :release do
    sh("cd .. && yarn typecheck")
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "android"
    )
  end
end
